AUTH_PROVIDER_PASSWORD = "password"
AUTH_PROVIDER_GOOGLE = "google"

OTP_CHANNEL_EMAIL = "email"
OTP_CHANNEL_PHONE = "phone"

OTP_PURPOSE_SIGNUP_VERIFY = "signup_verify"
OTP_PURPOSE_LOGIN_VERIFY = "login_verify"
OTP_PURPOSE_RESET_PASSWORD = "reset_password"
OTP_PURPOSE_CHANGE_CONTACT = "change_contact"

USER_STATUS_ACTIVE = "active"
