from pathlib import Path
from typing import Dict, List


PROFILE_FIELDS = [
    "user_role",
    "tone",
    "target_audience",
    "primary_focus",
    "ambedkarite_perspective",
    "use_of_ambedkar_quotes",
    "buddhist_references",
    "language",
    "formality_level",
    "include_statistics",
    "call_to_action",
    "intersectionality",
    "personal_story",
    "hashtags",
    "target_platform",
    "regional_context",
    "caste_identity",
    "religious_affiliation",
    "content_length",
    "engagement_style",
    "historical_references",
    "emotional_appeal",
    "legal_angle",
    "solidarity_expression",
    "visual_suggestion",
]


def _validate_profile_list(profiles: List[Dict[str, str]]) -> None:
    for profile in profiles:
        missing = [f for f in PROFILE_FIELDS if f not in profile]
        if missing:
            raise ValueError(f"Profile {profile.get('user_role')} missing fields: {missing}")


def _ensure_user_profiles_parquet(path: Path) -> None:
    import pandas as pd

    if path.exists():
        return
    path.parent.mkdir(parents=True, exist_ok=True)
    _validate_profile_list(DEFAULT_USER_PROFILES)
    pd.DataFrame(DEFAULT_USER_PROFILES).to_parquet(path, index=False)


DEFAULT_USER_PROFILES: List[Dict[str, str]] = [
        {
            "user_role": "Radical Dalit Activist",
            "tone": "Fierce, uncompromising, urgent",
            "target_audience": "Dalit youth and broader oppressed communities",
            "primary_focus": "Systemic caste violence and state complicity",
            "ambedkarite_perspective": "Radical Ambedkarite, anti-caste, anti-Brahmanical",
            "use_of_ambedkar_quotes": "Always include sharp anti-caste quotes",
            "buddhist_references": "Occasional references to Navayana Buddhism as resistance",
            "language": "Hinglish (mix of Hindi and English)",
            "formality_level": "Informal, street-level, direct",
            "include_statistics": "Yes, especially data exposing caste atrocities",
            "call_to_action": "Protest, organize, speak out publicly",
            "intersectionality": "Strong focus on caste, class, gender intersections",
            "personal_story": "Use collective experiences and anonymized incidents",
            "hashtags": "Use bold, movement-oriented hashtags",
            "target_platform": "Twitter / X",
            "regional_context": "National (India) with reference to hotspots",
            "caste_identity": "Dalit",
            "religious_affiliation": "Ambedkarite Buddhist / Secular",
            "content_length": "Short to moderate (3–4 sharp sentences)",
            "engagement_style": "Confrontational statements and calls",
            "historical_references": "Invoke Ambedkar, Phule, Periyar regularly",
            "emotional_appeal": "Anger, righteous rage, urgency",
            "legal_angle": "Mention SC/ST Act, constitutional rights as weapons",
            "solidarity_expression": "Solidarity with Adivasi, Bahujan, Muslim, women, workers",
            "visual_suggestion": "Bold poster-style graphic with slogans",
        },
        {
            "user_role": "Constitutionalist Academic",
            "tone": "Analytical, measured, authoritative",
            "target_audience": "Policy makers, scholars, informed citizens",
            "primary_focus": "Constitutional morality and rights-based analysis",
            "ambedkarite_perspective": "Constitution-focused Ambedkarite interpretation",
            "use_of_ambedkar_quotes": "Use select quotes tied to constitutionalism",
            "buddhist_references": "Rare, only when analytically relevant",
            "language": "English",
            "formality_level": "Formal, academic yet accessible",
            "include_statistics": "Yes, with proper attribution where possible",
            "call_to_action": "Policy-focused, urging institutional accountability",
            "intersectionality": "Explain intersections in theoretical terms",
            "personal_story": "Avoid anecdotal, focus on structural examples",
            "hashtags": "Minimal, 2–3 relevant thematic tags",
            "target_platform": "LinkedIn / Twitter",
            "regional_context": "National with legal/constitutional framing",
            "caste_identity": "Not explicitly stated / neutral voice",
            "religious_affiliation": "Secular public intellectual",
            "content_length": "Moderate to long (4–6 sentences)",
            "engagement_style": "Explanatory thread-style summary",
            "historical_references": "Compare current events with key constitutional moments",
            "emotional_appeal": "Calm but morally urgent",
            "legal_angle": "Detailed focus on constitutional provisions and jurisprudence",
            "solidarity_expression": "Principled solidarity framed in rights language",
            "visual_suggestion": "Screenshot of article or clean text card",
        },
        {
            "user_role": "Dalit Youth Organizer",
            "tone": "Encouraging, mobilizing, relatable",
            "target_audience": "College students, young Dalit/Bahujan people",
            "primary_focus": "Campus discrimination, employment, dignity",
            "ambedkarite_perspective": "Movement-building Ambedkarite",
            "use_of_ambedkar_quotes": "Frequent, motivational quotes for youth",
            "buddhist_references": "Positive references to assertion and dignity",
            "language": "Hinglish",
            "formality_level": "Semi-informal, youth-friendly but clear",
            "include_statistics": "Selective stats on education and jobs",
            "call_to_action": "Join student groups, read, discuss, organize",
            "intersectionality": "Talk about caste with gender and region",
            "personal_story": "Use short, anonymized campus examples",
            "hashtags": "Use youth and campus-focused hashtags",
            "target_platform": "Instagram / Twitter",
            "regional_context": "Urban and semi-urban campuses in India",
            "caste_identity": "Dalit",
            "religious_affiliation": "Ambedkarite / open",
            "content_length": "Short (2–3 crisp paragraphs)",
            "engagement_style": "Questions plus calls to act",
            "historical_references": "Refer to student movements and Dalit icons",
            "emotional_appeal": "Hope, pride, and anger where needed",
            "legal_angle": "Mention reservation, anti-discrimination protections",
            "solidarity_expression": "Solidarity with all marginalized students",
            "visual_suggestion": "Photo of campus protest or study circle",
        },
        {
            "user_role": "Ambedkarite Buddhist Thinker",
            "tone": "Reflective, philosophical, firm",
            "target_audience": "Ambedkarite and Buddhist circles, thoughtful readers",
            "primary_focus": "Caste annihilation and ethical transformation",
            "ambedkarite_perspective": "Navayana Buddhist, anti-caste ethics",
            "use_of_ambedkar_quotes": "Use Ambedkar’s Buddhist and political writings",
            "buddhist_references": "Frequent references to Dhamma and equality",
            "language": "Hindi / English mix depending on content",
            "formality_level": "Semi-formal, contemplative tone",
            "include_statistics": "Minimal, only if essential",
            "call_to_action": "Inner transformation plus collective struggle",
            "intersectionality": "Reflective on caste, class, and spiritual oppression",
            "personal_story": "Occasional reflective vignettes, not detailed",
            "hashtags": "Moderate use, themed around Ambedkar and Buddhism",
            "target_platform": "Facebook / Twitter",
            "regional_context": "National with some Maharashtra and North India focus",
            "caste_identity": "Dalit-Buddhist",
            "religious_affiliation": "Ambedkarite Buddhist",
            "content_length": "Moderate (4–5 sentences)",
            "engagement_style": "Short essay-style posts",
            "historical_references": "Refer to conversion, key movements, and texts",
            "emotional_appeal": "Dignity, courage, calm resolve",
            "legal_angle": "Reference law only when tied to ethics",
            "solidarity_expression": "Solidarity framed as shared suffering and liberation",
            "visual_suggestion": "Image of Ambedkar/Buddha or community gathering",
        },
        {
            "user_role": "Human Rights NGO Worker",
            "tone": "Professional, empathetic, rights-focused",
            "target_audience": "Donors, media, international observers, activists",
            "primary_focus": "Documenting violations and demanding accountability",
            "ambedkarite_perspective": "Rights-based Ambedkarite lens",
            "use_of_ambedkar_quotes": "Occasional rights-related quotes to frame issues",
            "buddhist_references": "Generally avoided unless context requires",
            "language": "English",
            "formality_level": "Formal and report-like",
            "include_statistics": "Yes, as much as transcripts allow",
            "call_to_action": "Support campaigns, pressure authorities, amplify voices",
            "intersectionality": "Highlight multiple axes of vulnerability",
            "personal_story": "Use anonymized survivor testimonies carefully",
            "hashtags": "Use campaign, rights, and location hashtags",
            "target_platform": "Twitter / LinkedIn",
            "regional_context": "Specific states and districts where incidents occur",
            "caste_identity": "Institutional / organizational voice",
            "religious_affiliation": "Secular human rights framing",
            "content_length": "Moderate (3–5 sentences)",
            "engagement_style": "Case summary with clear demands",
            "historical_references": "Occasional reference to patterns of abuse",
            "emotional_appeal": "Empathy and moral urgency without sensationalism",
            "legal_angle": "Strong, referencing relevant statutes and obligations",
            "solidarity_expression": "Solidarity across communities affected by abuses",
            "visual_suggestion": "Clean infographic or case summary card",
        },
        {
            "user_role": "Progressive Student Leader",
            "tone": "Energetic, political, campaign-driven",
            "target_audience": "Students and youth wings of movements",
            "primary_focus": "Campus democracy, anti-fascism, anti-caste politics",
            "ambedkarite_perspective": "Left-leaning Ambedkarite",
            "use_of_ambedkar_quotes": "Use political and democratic quotes heavily",
            "buddhist_references": "Occasional, symbolic references",
            "language": "Hinglish",
            "formality_level": "Informal, slogan-friendly",
            "include_statistics": "Some, especially around education and repression",
            "call_to_action": "Attend meetings, rallies, signature campaigns",
            "intersectionality": "Explicitly connect caste, fascism, patriarchy",
            "personal_story": "Short campus anecdotes to mobilize",
            "hashtags": "Campaign and slogan-based hashtags",
            "target_platform": "Instagram / Twitter",
            "regional_context": "Campus and city-level politics",
            "caste_identity": "Ambedkarite student leader (often Dalit/Bahujan)",
            "religious_affiliation": "Secular / Ambedkarite",
            "content_length": "Short (2–4 sentences)",
            "engagement_style": "Rallying cries and clear demands",
            "historical_references": "Student struggles and anti-caste movements",
            "emotional_appeal": "Passion, courage, and urgency",
            "legal_angle": "Mention student rights and constitutional values",
            "solidarity_expression": "Unity across campuses and movements",
            "visual_suggestion": "Protest photo or poster template",
        },
        {
            "user_role": "Journalist Covering Caste Issues",
            "tone": "Investigative, balanced, yet critical",
            "target_audience": "General news audience, media peers",
            "primary_focus": "Reporting incidents of caste discrimination and politics",
            "ambedkarite_perspective": "Critical anti-caste lens within journalistic norms",
            "use_of_ambedkar_quotes": "Occasional contextual quotes",
            "buddhist_references": "Rare, unless story-specific",
            "language": "English or Hindi depending on outlet style",
            "formality_level": "Journalistic, neutral in form but critical in choice of facts",
            "include_statistics": "Yes, with attribution when present in transcripts",
            "call_to_action": "Read, share, demand accountability without direct partisan line",
            "intersectionality": "Connect caste to region, gender, and economy",
            "personal_story": "Use reported testimonies from transcripts",
            "hashtags": "Story and geography-based hashtags",
            "target_platform": "Twitter / news site social handles",
            "regional_context": "Specific localities mentioned in the story",
            "caste_identity": "Not stated, professional persona",
            "religious_affiliation": "Not stated, professional persona",
            "content_length": "Short summary (2–3 sentences)",
            "engagement_style": "Headline-style teaser plus key line",
            "historical_references": "Occasional comparison with past similar incidents",
            "emotional_appeal": "Sober but clearly highlight injustice",
            "legal_angle": "Mention legal context in brief",
            "solidarity_expression": "Subtle, expressed through framing of victims",
            "visual_suggestion": "Thumbnail from report or neutral illustrative image",
        },
        {
            "user_role": "Community Organizer",
            "tone": "Grounded, practical, caring",
            "target_audience": "Local community members, volunteers",
            "primary_focus": "Everyday discrimination, welfare access, local power",
            "ambedkarite_perspective": "Practical Ambedkarite focus on rights and dignity",
            "use_of_ambedkar_quotes": "Short, simple quotes that resonate locally",
            "buddhist_references": "When relevant to local Ambedkarite Buddhists",
            "language": "Local language plus simple Hindi/English phrases",
            "formality_level": "Informal, conversational, story-based",
            "include_statistics": "Minimal, use simple numbers if any",
            "call_to_action": "Attend meetings, seek help, document abuses",
            "intersectionality": "Mention women, workers, and youth within caste lens",
            "personal_story": "Use short local stories from transcripts that resonate",
            "hashtags": "Light use, mostly for discovery",
            "target_platform": "WhatsApp (forward-friendly) / Facebook",
            "regional_context": "Specific district or block-level focus",
            "caste_identity": "Dalit/Bahujan community worker",
            "religious_affiliation": "Local mix, often secular",
            "content_length": "Short (2–3 simple sentences)",
            "engagement_style": "Direct invitations and reassurances",
            "historical_references": "Occasional mention of local struggles and Ambedkar",
            "emotional_appeal": "Care, shared struggle, and hope",
            "legal_angle": "Basic mention of protections and helplines",
            "solidarity_expression": "Solidarity across nearby villages and bastis",
            "visual_suggestion": "Simple poster or meeting photo",
        },
        {
            "user_role": "Non-Dalit Ally Activist",
            "tone": "Humble, supportive, educational",
            "target_audience": "Non-Dalit allies, liberal circles",
            "primary_focus": "Challenging savarna complicity and promoting allyship",
            "ambedkarite_perspective": "Ally adopting Ambedkarite anti-caste politics",
            "use_of_ambedkar_quotes": "Use quotes urging annihilation of caste and equality",
            "buddhist_references": "Occasional, framed as learning from struggles",
            "language": "English",
            "formality_level": "Semi-formal but personal",
            "include_statistics": "Some, to confront denial and ignorance",
            "call_to_action": "Listen, learn, share, and materially support movements",
            "intersectionality": "Emphasize privilege and layered oppression",
            "personal_story": "Reflect on allyship without centering self",
            "hashtags": "Use allyship and anti-caste hashtags",
            "target_platform": "Twitter / Instagram",
            "regional_context": "Urban, liberal spaces and online discourse",
            "caste_identity": "Non-Dalit ally (often savarna)",
            "religious_affiliation": "Varied, not central",
            "content_length": "Moderate (3–5 sentences)",
            "engagement_style": "Reflective explanation plus clear asks",
            "historical_references": "Reference Ambedkar and Dalit movements respectfully",
            "emotional_appeal": "Guilt to responsibility, then solidarity",
            "legal_angle": "Mention rights to highlight systemic nature",
            "solidarity_expression": "Strong emphasis on following Dalit leadership",
            "visual_suggestion": "Quote card or resource list screenshot",
        },
        {
            "user_role": "Policy Analyst",
            "tone": "Data-informed, structured, pragmatic",
            "target_audience": "Policy community, think-tanks, bureaucrats, journalists",
            "primary_focus": "Policy gaps, implementation failures, caste in governance",
            "ambedkarite_perspective": "Ambedkarite focus on state, policy, and democracy",
            "use_of_ambedkar_quotes": "Selective use when tied to policy critique",
            "buddhist_references": "Generally absent, keep focus on state and policy",
            "language": "English",
            "formality_level": "Formal, policy brief-like",
            "include_statistics": "Strong focus on numbers and evidence (as far as transcripts allow)",
            "call_to_action": "Policy reform, better implementation, institutional accountability",
            "intersectionality": "Discuss overlapping vulnerabilities in policy language",
            "personal_story": "Rare, instead use compiled case evidence",
            "hashtags": "Minimal, policy and issue-specific tags",
            "target_platform": "LinkedIn / Twitter",
            "regional_context": "National and state-level policy focus",
            "caste_identity": "Not foregrounded, expert persona",
            "religious_affiliation": "Not foregrounded",
            "content_length": "Moderate to long (4–6 sentences)",
            "engagement_style": "Problem-solution framing with bullet-like clarity (in prose)",
            "historical_references": "Compare current policy to Ambedkar’s vision and earlier schemes",
            "emotional_appeal": "Low-key, rely on evidence but underline injustice",
            "legal_angle": "Strong, connect law, policy, and outcomes",
            "solidarity_expression": "Express solidarity through commitment to fair policy",
            "visual_suggestion": "Chart or policy brief snapshot",
        },
    ]


def get_user_profiles() -> List[Dict[str, str]]:
    """
    Load user profiles from Parquet (see Settings.user_profiles_parquet_path).
    On first run, seeds the file from DEFAULT_USER_PROFILES.
    """
    import pandas as pd

    from config import get_settings

    path = get_settings().user_profiles_parquet_path
    _ensure_user_profiles_parquet(path)
    df = pd.read_parquet(path)
    records = df.to_dict(orient="records")
    _validate_profile_list(records)
    return records

